#ifndef DEF_FUNC_CODE
#define DEF_FUNC_CODE(...)
#endif

DEF_FUNC_CODE (STACK_CTOR_CODE, 0x001, "StackCtor()\n")
DEF_FUNC_CODE (STACK_DTOR_CODE, 0x002, "StackDtor()\n")
DEF_FUNC_CODE (STACK_PUSH_CODE, 0x004, "StackPush()\n")
DEF_FUNC_CODE (STACK_POP_CODE, 0x008, "StackPush()\n")
DEF_FUNC_CODE (STACK_INCREASE_CODE, 0x010, "StackIncrease()\n")
DEF_FUNC_CODE (STACK_DECREASE_CODE, 0x020, "StackDecrease()\n")
DEF_FUNC_CODE (STACK_DUMP_CODE, 0x040, "StackDump()\n")
DEF_FUNC_CODE (STACK_UNIT_TEST_CODE, 0x080, "UnitTest()\n")
DEF_FUNC_CODE (STACK_SET_PRINTER_CODE, 0x100, "SetStackPrinter()\n")
DEF_FUNC_CODE (STACK_PRINT_EXIT_CODE_CODE, 0x200, "PrintExitCode()\n")
DEF_FUNC_CODE (STACK_VALIDATE_CODE, 0x400, "StackValidate()\n")
DEF_FUNC_CODE (STACK_EXTERNAL_FUNC_CODE, 0x800, "Some external function\n")


